### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aaronchipper**
Renamed the widget to "UI Screens"

### CODE REVIEW

**Comment by pedrotorchio** [comment]
UI Screens seem to have very little meaning to it, has this gone through some brainstorming?

**Comment by aaronchipper** [comment]
This is a marketing decision. 'Nuff said.

**Review by pedrotorchio — COMMENTED** [review]
Don't believe UI Screens say much about what this is (User Interface Screens, don't really mean anything. UI Screen could as well be a page on the portal). Besides that, changes seem alright.

**Review by pedrotorchio — APPROVED** [review]
Don't believe UI Screens say much about what this is (User Interface Screens, don't really mean anything. UI Screen could as well be a page on the portal). Besides that, changes seem alright.

**Pull request merged**
